config/routes.rb
Grassroots::Application.routes.draw do
  root to: 'pages#home' 
  get 'sign_in', to: 'sessions#new'
  post 'log_in', to: 'sessions#create'
  get 'log_out', to: 'sessions#destroy'

  mount Attachinary::Engine => "/attachinary"

  namespace :organization_admin do
    resources :projects, only: [:new, :create, :edit, :update]
    resources :organizations, only: [:edit, :update, :new, :create]
    resources :volunteer_applications, only: [:index]
  end

  namespace :volunteer do
    resources :volunteer_applications, only: [:index]
  end

  resources :users, except: [:destroy] do
    collection do
      get 'search', to: 'users#search', as: 'search'
    end
  end
  delete 'remove', to: 'users#remove'
  
  resources :organizations, only: [:show, :index] do
    collection do
      get 'search', to: 'organizations#search', as: 'search'
    end
  end
  
  resources :projects, only: [:index, :show] do
    collection do
      get 'search', to: 'projects#search', as: 'search'
    end
  end
  get 'join', to: 'projects#join', as: 'join'

  resources :messages, only: [:new, :create, :index] 
  resources :volunteer_applications, only: [:new, :create]
  resources :contracts, only: [:create, :new, :destroy, :update]
  resources :work_submissions, only: [:new, :create]
  resources :conversations, only: [:show, :index]

  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'password_resets#expired_token'

  resources :questions, only: [:index, :show, :new, :create, :edit, :update] do
    
    member do
      post '/votes', to: 'questions#vote'
    end

    resources :comments, only: [:create] do
      member do
        post '/votes', to: 'comments#vote'
      end
    end

    resources :answers, only: [:create] do
      member do
        post '/votes', to: 'answers#vote'
      end
      
      resources :comments, only: [:create] do
        member do
          post '/votes', to: 'comments#vote'
        end
      end
    end
  end

  resources :work_conversations, only: [:index]
  resources :categories, only: [:show]
  resources :badges, only: [:show]
  resources :relationships, only: [:create, :destroy]
  resources :newsfeed_items, only: [:index] do
    resources :comments, only: [:create]
  end
  resources :status_updates, only: [:create]

  resources :skills, only: [:create]
end

app/views/shared/_conversation_thumbnail.html.haml
.row.msg-thumbnail
  .col-lg-2
    %img.header-img{:src => "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash2/t1.0-1/c204.44.552.552/s160x160/303330_10100328964694072_324662327_n.jpg"}
  .col-lg-10.content-wrapper
    %h2
      %strong 
        - if conversation.sender_user_name_of_recent_message
          = link_to conversation.sender_user_name_of_recent_message, user_path(conversation.the_id_of_sender)
    %h4.header-spacing
      %strong
        = link_to conversation.messages.first.subject, conversation_path(conversation.id)
    %p 
      = conversation.message_body
    - if conversation.volunteer_application_id
      .btn-group
        %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
          Volunteer Application
          %span.caret
        %ul.dropdown-menu{role: "menu"}
          %li
            = link_to "Reply (before accepting)", conversation_path(conversation.id)
          %li
            %a{href: "#"} Ignore Request
          %li.divider
          %li
            = link_to "Accept", contracts_path(volunteer_application_id: conversation.volunteer_application_id, conversation_id: conversation.id), method: :post
    - if conversation.contract_id
      - if conversation.with_opportunity_to_drop_job
        .btn-group
          %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
            Drop Contract
            %span.caret
          %ul.dropdown-menu{role: "menu"}
            %li
              = link_to "Reply (before deciding)", conversation_path(conversation.id)
            %li.divider
            %li
            - if current_user_contractor(conversation)
              = link_to "Drop Volunteer", contract_path(id: conversation.contract_id), method: :delete
            - else
              = link_to "Drop Project", contract_path(id: conversation.contract_id), method: :delete
      - if conversation.with_work_submitted
        - if current_user_contractor(conversation)
          .btn-group
            %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
              Contract Complete
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to "Reply (before confirming completion)", conversation_path(conversation.id)
              %li
                %a{href: "#"} Incompleted
              %li.divider
              %li
                = link_to "Completed", contract_path(id: conversation.contract_id), method: :patch

app/views/shared/_empty_project_thumbnail.html.haml
.col-lg-12.col-sm-12
  %p.no-content Nothing to report.

app/views/shared/_footer.html.haml
.col-lg-3#footer-mission
  %p Our mission is to serve as a catalyst for positive social change by offering free technology tools, resources and best practices for nonprofit organizations to leverage their charitable efforts and serve their community more effectively.
.col-lg-3#footer-info
  %ul 
    %li 
      %a{:href => "#"} About
    %li 
      %a{:href => "#"} Services
    %li 
      %a{:href => "#"} Our Team 
    %li 
      %a{:href => "#"} Blog
    %li 
      %a{:href => "#"} Partner
    %li 
      %a{:href => "#"} Successes
.col-lg-3#footer-contact
  %ul 
    %li 
      %a{:href => "#"} Contact Us
    %li 
      %a{:href => "#"} Support
    %li 
      %a{:href => "#"} Membership Terms
.col-lg-3
  %div#social-icons
    = image_tag("facebook-icon.ico")
    = image_tag("twitter-icon.ico")
    = image_tag("linkedin-icon.ico")
    = image_tag("googleplus-icon.ico")
  %p#copy 2014 Grassroots.org

app/views/shared/_header.html.haml
%link{:href => "/Users/robertjewell/sites/grassroots/app/assets/stylesheets", :rel => "stylesheet"}  
  %nav.navbar.navbar-default#header{:role => "navigation"}
    %button.navbar-toggle{"data-target" => "#interior-sidebar-wrapper", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
      / <a class="navbar-brand" href="#">Brand</a>
    / Collect the nav links, forms, and other content for toggling
    %nav
      
      - if current_user
        //#bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.nav-tabs.account-tabs
          %li
            = link_to "Inbox", conversations_path if current_user          
          %li.dropdown
            %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
              = "Welcome, #{current_user.first_name}"
              %b.caret
            %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
              %li
                = link_to "Profile", user_path(current_user.id) if current_user
                = link_to "Organization", organization_path(current_user.organization.id) if current_user.organization
                = link_to "Log out", log_out_path
      - else 
        %ul.nav.account-tabs
          %li
            %a{:href => "#"} Donate
          %li
            %a{:href => "#"} Help
          %li
            %a{:href => "#"} Blog 
          %li
            = link_to "Sign In", sign_in_path unless current_user
      / /.navbar-collapse
%body

app/views/shared/_landing_footer.html.haml
.col-lg-4
.col-lg-4#footer-contact
  %ul 
    %li 
      %a{:href => "#"} Membership Terms
    %li 
      %a{:href => "#"} About
    %li#copy 2014 Grassroots.org
        
  %div#social-ico-wrapper
    %div#social-icons
      = image_tag("facebook-icon.ico")
      = image_tag("twitter-icon.ico")
      = image_tag("linkedin-icon.ico")
      = image_tag("googleplus-icon.ico")
 
.col-lg-4
  

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss="alert") &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/shared/_organization_thumbnail.html.haml
.col-lg-3.col-sm-3
  .thumbnail.thumbnail-staff
    %img.img-responsive.img-staff{:src => "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash2/t1.0-1/c204.44.552.552/s160x160/303330_10100328964694072_324662327_n.jpg"}
    .caption
      %h5
        = link_to "#{organization.name}", organization_path(organization.id)
      %h5

app/views/shared/_project_draft_thumbnail.html.haml
%ul
	%li= link_to "#{draft.project.title}", new_organization_admin_project_path(project_id: draft.project.id)

app/views/shared/_project_thumbnail.html.haml
.col-lg-3.col-sm-6.project-thumb-wrapper
  .thumbnail.thumbnail-project
    .pic
      - if project.organization.logo?
        = link_to cl_image_tag(project.organization.logo.path, { size: '150x150', crop: :fit }), project_path(project.id)
      - else
        = link_to image_tag(project.organization.small_cover.to_s, size: "100%"), project_path(project.id)
    .caption
    - if project.applicants.count > 0
      .volunteer-project-requests
        %span.glyphicon.glyphicon-user.volunteer-glyph
        .volunteer-plus
          %span.glyphicon.glyphicon-plus.volunteer-plus-glyph 
            %span.volunteer-number
              = "#{project.applicants.count}"
    %h4.title  
      = project_title(project)
    %h5.org-link
      = link_to project.organization.name, organization_path(project.organization.id)
    %p.description 
      - if project.description > project.description.first(60)
        = "#{project.description.first(60)}..."
      - else 
        = project.description
    .project-thumb-info
      %dl
        %dt Skill Set
        %dd 
          = project.project_type
      %dl.deadline
        %dt Deadline
        %dd 
          = fix_date_time(project.deadline)
    - if project.project_admin == current_user
      %btn= link_to "View Project", project_path(project.id), class: 'btn btn-primary btn-lg btn-block btn-project'
    - else 
      -if  project.organization == current_user.organization
        %btn= link_to "View Project", project_path(project.id), class: 'btn btn-primary btn-lg btn-bl ock btn-project'
    - if project.project_admin != current_user
      - if project.organization != current_user.organization
        - if project.state == "open"
          %btn= link_to "Join Project", new_volunteer_application_path(project_id: project.id), class: 'btn btn-success btn-lg btn-block btn-project'
        - elsif project.in_production?
          %btn= link_to "Project Complete", new_work_submission_path(contract_id: project.in_production_contract_id), class: 'btn btn-warning btn-lg btn-block btn-project'
        - elsif project.has_submitted_work?
          %btn= link_to "Pending Completion", new_message_path(user_id: project.id), class: 'btn btn-info btn-lg btn-block btn-project'
        - elsif project.is_complete?
          %btn= link_to "Finished", "#", class: 'btn btn-default btn-lg btn-block btn-project'
        - else
          %btn= link_to "Unfinished", "#", class: 'btn btn-default btn-lg btn-block btn-project'

app/views/shared/_sidebar.html.haml
- if current_user
  %link{:href => "/Users/robertjewell/sites/grassroots/app/assets/stylesheets", :rel => "stylesheet"}   
  %nav.navbar.navbar-default#sidebar-custom{:role => "navigation"}
    / Brand and toggle get grouped for better mobile display
    / <a class="navbar-brand" href="#">Brand</a>
    / Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse#interior-sidebar-wrapper
      %ul.nav.nav-pills.nav-stacked
        %li
          = link_to "Projects", projects_path if current_user
        %li
          = link_to "Organizations", organizations_path if current_user
        %li
          = link_to "Talent", users_path if current_user
        %li
          = link_to "Forum", questions_path if current_user
        %li
          = link_to "Newsfeed", newsfeed_items_path if current_user



app/views/shared/_user_thumbnail.html.haml
.col-lg-3.col-sm-3
  .thumbnail.thumbnail-staff
    %img.img-responsive.img-staff{:src => "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash2/t1.0-1/c204.44.552.552/s160x160/303330_10100328964694072_324662327_n.jpg"}
    .caption
      %h5
        = link_to "#{user.first_name} #{user.last_name}", user_path(user.id)
      %h5
        = link_to "#{user.organization.name}", organization_path(user.organization.id) if user.organization
      %h5
        = "Organization's Administrator" if user.organization_administrator
        = "Freelancer" if user.volunteer
        = "#{user.position}" if user.organization_staff
        %btn
          = link_to "Message",new_message_path(user_id: user.id), class: 'btn btn-primary btn-block'