config/routes.rb
Grassroots::Application.routes.draw do
  root to: 'pages#home' 
  get 'sign_in', to: 'sessions#new'
  post 'log_in', to: 'sessions#create'
  get 'log_out', to: 'sessions#destroy'

  mount Attachinary::Engine => "/attachinary"

  namespace :organization_admin do
    resources :projects, only: [:new, :create, :edit, :update]
    resources :organizations, only: [:edit, :update, :new, :create]
    resources :volunteer_applications, only: [:index]
  end

  namespace :volunteer do
    resources :volunteer_applications, only: [:index]
  end

  resources :users, except: [:destroy] do
    collection do
      get 'search', to: 'users#search', as: 'search'
    end
  end
  delete 'remove', to: 'users#remove'
  
  resources :organizations, only: [:show, :index] do
    collection do
      get 'search', to: 'organizations#search', as: 'search'
    end
  end
  
  resources :projects, only: [:index, :show] do
    collection do
      get 'search', to: 'projects#search', as: 'search'
    end
  end
  get 'join', to: 'projects#join', as: 'join'

  resources :messages, only: [:new, :create, :index] 
  resources :volunteer_applications, only: [:new, :create]
  resources :contracts, only: [:create, :new, :destroy, :update]
  resources :work_submissions, only: [:new, :create]
  resources :conversations, only: [:show, :index]

  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'password_resets#expired_token'

  resources :questions, only: [:index, :show, :new, :create, :edit, :update] do
    
    member do
      post '/votes', to: 'questions#vote'
    end

    resources :comments, only: [:create] do
      member do
        post '/votes', to: 'comments#vote'
      end
    end

    resources :answers, only: [:create] do
      member do
        post '/votes', to: 'answers#vote'
      end
      
      resources :comments, only: [:create] do
        member do
          post '/votes', to: 'comments#vote'
        end
      end
    end
  end

  resources :work_conversations, only: [:index]
  resources :categories, only: [:show]
  resources :badges, only: [:show]
  resources :relationships, only: [:create, :destroy]
  resources :newsfeed_items, only: [:index] do
    resources :comments, only: [:create]
  end
  resources :status_updates, only: [:create]

  resources :skills, only: [:create]
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Voteable
  belongs_to :author, foreign_key: 'user_id', class_name: 'User'
  belongs_to :question
  has_many :comments, as: :commentable
  has_many :newsfeed_items, as: :newsfeedable

  validates_presence_of :description
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authorize, only: [:create, :vote, :comment]

  def create
    posts_an_answer_to_question
    makes_answer_a_newsfeed_item(@answer)
    redirect_to :back
  end

  def vote
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:question_id])

    if @answer.user_id == current_user.id
      flash[:error] = "You cannot vote on your own answer."
    else
      vote = Vote.create(voteable: @answer, user_id: current_user.id, vote: params[:vote]) 
      vote.valid? ? flash[:success] = "Thank you for voting." : flash[:error] = "You can only vote once on this answer."
    end

    redirect_to :back
  end

private

  def answer_params
    params.require(:answer).permit(:description)    
  end

  def posts_an_answer_to_question
    @answer = Answer.new(answer_params)
    @answer.author = current_user
    @answer.question_id = params[:question_id]
    @answer.save
  end

  def makes_answer_a_newsfeed_item(answer)
    newsfeed_item = NewsfeedItem.create(user_id: current_user.id)
    answer.newsfeed_items << newsfeed_item
  end
end

app/views/answers/_answer.html.haml
%div.answer-wrapper
  %div.only-answer-wrapper 
    %div.forum-vote
      %ul
        %li
          = link_to votes_question_answer_path(question_id: @question.id, id: answer.id, vote: true), method: 'post' do
            %span.glyphicon.glyphicon.glyphicon-chevron-up
        %li 
          %span.vote-number= answer.total_votes
    %p
      = "#{answer.description}"
    -#  
      %small 
        created at
        = "#{fix_date_time(answer.created_at)}"
    %div.avatar-wrapper
      - if @question.author.avatar?
        = cl_image_tag(@question.author.avatar.path, size: "20x20")
      - else
        = image_tag(@question.author.small_cover, class: "testing")
      %div
        %ul
          %li
            = link_to "#{answer.author.first_name} #{answer.author.last_name}", user_path(answer.author)
          %li Grassroots.org
  %div.comment-wrapper
    - answer.comments.each do |comment|
      = render 'comments/comment', comment: comment
  %div.new-comment-wrapper  
    %a{:title => "Use the comments to ask for a clarification on the answer", :class => "comment-link"} add comment
    %div.comment-form
      = form_for @comment, url: question_answer_comments_path(answer_id: answer.id, question_id: @question.id) do |f|
        = f.text_area :content, id: "comment_answer"
        %br/
        = f.submit "Comment on the answer", class: "btn btn-primary"