config/routes.rb
Grassroots::Application.routes.draw do
  root to: 'pages#home' 
  get 'sign_in', to: 'sessions#new'
  post 'log_in', to: 'sessions#create'
  get 'log_out', to: 'sessions#destroy'

  mount Attachinary::Engine => "/attachinary"

  namespace :organization_admin do
    resources :projects, only: [:new, :create, :edit, :update]
    resources :organizations, only: [:edit, :update, :new, :create]
    resources :volunteer_applications, only: [:index]
  end

  namespace :volunteer do
    resources :volunteer_applications, only: [:index]
  end

  resources :users, except: [:destroy] do
    collection do
      get 'search', to: 'users#search', as: 'search'
    end
  end
  delete 'remove', to: 'users#remove'
  
  resources :organizations, only: [:show, :index] do
    collection do
      get 'search', to: 'organizations#search', as: 'search'
    end
  end
  
  resources :projects, only: [:index, :show] do
    collection do
      get 'search', to: 'projects#search', as: 'search'
    end
  end
  get 'join', to: 'projects#join', as: 'join'

  resources :messages, only: [:new, :create, :index] 
  resources :volunteer_applications, only: [:new, :create]
  resources :contracts, only: [:create, :new, :destroy, :update]
  resources :work_submissions, only: [:new, :create]
  resources :conversations, only: [:show, :index]

  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'password_resets#expired_token'

  resources :questions, only: [:index, :show, :new, :create, :edit, :update] do
    
    member do
      post '/votes', to: 'questions#vote'
    end

    resources :comments, only: [:create] do
      member do
        post '/votes', to: 'comments#vote'
      end
    end

    resources :answers, only: [:create] do
      member do
        post '/votes', to: 'answers#vote'
      end
      
      resources :comments, only: [:create] do
        member do
          post '/votes', to: 'comments#vote'
        end
      end
    end
  end

  resources :work_conversations, only: [:index]
  resources :categories, only: [:show]
  resources :badges, only: [:show]
  resources :relationships, only: [:create, :destroy]
  resources :newsfeed_items, only: [:index] do
    resources :comments, only: [:create]
  end
  resources :status_updates, only: [:create]

  resources :skills, only: [:create]
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :organization
  belongs_to :administrator, foreign_key: 'user_id', class_name: 'Organization'
  has_one :project_draft

  has_many :volunteer_applications
  has_many :users, through: :volunteer_applications
  has_many :applicants, class_name: 'VolunteerApplication', foreign_key: 'applicant_id'
  has_many :applicants, through: :volunteer_applications

  has_many :contracts
  has_many :users, through: :contracts
  
  has_many :volunteers, class_name: 'Contract', foreign_key: 'volunteer_id'
  has_many :volunteers, through: :contracts, source: :volunteer

  has_many :contractors, class_name: 'Contract', foreign_key: 'contractor_id'
  has_many :contractors, through: :contracts, source: :contractor

  has_many :newsfeed_items, as: :newsfeedable

  has_many :requirements
  has_many :skills, through: :requirements

  def project_admin
    organization.organization_administrator
    User.find(organization.organization_administrator.id)
  end

  def open
    self.state == "open"
  end

  def self.search_by_title_or_description(search_term)
    return [] if search_term.blank?
    if where("title or description LIKE ?", "%#{search_term}%") != []
      where("title or description LIKE ?", "%#{search_term}%")
    elsif where("title LIKE ?", "%#{search_term}%") != []
      where("title LIKE ?", "%#{search_term}%")
    elsif where("description LIKE ?", "%#{search_term}%") != []
      where("description LIKE ?", "%#{search_term}%")
    else
      []
    end
  end

  def in_production?
    self.contracts.where(active: true, work_submitted: false, project_id: self.id).present?
  end

  def has_submitted_work?
    self.contracts.where(active: true, work_submitted: true, project_id: self.id).present?
  end

  def is_complete?
    self.contracts.where(active: false, work_submitted: true, complete: true, project_id: self.id).present?
  end

  def in_production_contract_id
    self.contracts.where(active: true, work_submitted: false, project_id: self.id).first
  end

  def is_unfinished?
    self.contracts.where(active: false, incomplete: true).present?
  end
end

app/controllers/organization_admin/projects_controller.rb
class OrganizationAdmin::ProjectsController < OrganizationAdminController
  before_action :find_organization, only: [:create]
  
  def new
    params[:project_id] ? @project = Project.find(params[:project_id]) : @project = Project.new(organization_id: current_user.administrated_organization.id)
    @skill = Skill.new
    @all_skills = Skill.all
  end

  def create
    if publishing_a_project?
      if publishing_a_project_draft?
        @project = Project.find(params[:project][:id])
        @project.update!(project_params.merge!(causes: @organization.cause, state: "open"))
        creates_a_newsfeed_item_for_the_project(@project)
        flash[:notice] = "You successfully created a project"
        redirect_to project_path(@project.id)
      else
        @project = Project.new(project_params) 
        @project.save
        @project.update_columns(state: "open", causes: @organization.cause)
        creates_a_newsfeed_item_for_the_project(@project)
        flash[:notice] = "You successfully created a project"
        redirect_to project_path(@project.id)
      end

    elsif saving_a_draft?
      if re_saving_a_draft?
        @project = Project.find(params[:project][:id])
        @project.update!(project_params.merge!(causes: @organization.cause))
      else
        create_new_draft_for_the_project
      end

      flash[:notice] = "This project has been saved as a draft"
      redirect_to new_organization_admin_project_path(project_id: @project.id)

    elsif adding_a_required_skill?
      if to_an_existing_draft?
        @project = Project.find(params[:project_id])
      else
        create_a_draft_for_the_project
      end
      if does_this_skill_exist?
        add_skill_to_the(@project)
        redirect_to new_organization_admin_project_path(project_id: @project.id)
      else
        create_skill_and_associate_to_the(@project)
        redirect_to new_organization_admin_project_path(project_id: @project.id)
      end

    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])  
    @all_skills = Skill.all
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    flash[:success] = "You updated your project"
    redirect_to project_path(@project.id)
  end

private

  def project_params
    params.require(:project).permit(:title, :organization_id, 
      :user_id, :description, :skills, :deadline, :project_type)
  end

  def creates_a_newsfeed_item_for_the_project(project)
    @newsfeed_item = NewsfeedItem.create(user_id: current_user.id)
    project.newsfeed_items << @newsfeed_item
  end

  def find_organization
    @organization = Organization.find_by(params[:id])
  end

  def publishing_a_project_draft?
    params[:project][:id]
  end

  def re_saving_a_draft?
    params[:project][:id]
  end

  def publishing_a_project?
    params[:commit] == "Publish Project"
  end

  def saving_a_draft?
    params[:commit] == "Save Draft"
  end

  def adding_a_required_skill?
    params[:commit] == "Add Skill"
  end

  def to_an_existing_draft?
    params[:project_id]
  end

  def does_this_skill_exist?
    Skill.where(name: params[:skill][:name]) != []
  end

  def add_skill_to_the(project)
    skill = Skill.where(name: params[:skill][:name]).first
    project.skills << skill
  end

  def create_skill_and_associate_to_the(project)
    skill = Skill.create(name: params[:skill][:name])
    project.skills << skill
  end

  def create_a_draft_for_the_project
    @project = Project.create(organization_id: current_user.administrated_organization.id)
    @project_draft = ProjectDraft.create(organization_id: @organization.id, project_id: @project.id)
  end

  def create_new_draft_for_the_project
    @project = Project.new(project_params.merge!(causes: @organization.cause))
    @project.save 
    @project_draft = ProjectDraft.create(organization_id: @organization.id, project_id: @project.id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :current_user

  def index
    #@projects = Project.where(state: "open").where("self.deadline > Time.now")
    @projects = Project.where(state: "open").where("deadline > now")
    open_projects = Project.where(state: "open").to_a
    @projects = open_projects.select do |member|
      member.state == "open" && member.deadline > Date.today
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def search
    if params[:search_term] && params[:search_term] != ""
      search_term = params[:search_term]
      #@results = Project.search_by_title_or_description(params[:search_term])
      #@results = Project.where("title OR description LIKE ?", "%#{search_term}%")
      @results_by_title = Project.where("title LIKE ?", "%#{search_term}%")
      @results_by_description = Project.where("description LIKE ?", "%#{search_term}%")
      @results = @results_by_title.concat(@results_by_description)
      @results.uniq!
      @results.to_a
    else
      filter = {project_type: params[:project_type]} if params[:project_type]
      filter = {causes: params[:causes]}  if params[:causes]
      
      @results = Project.where(filter).to_a
    end
  end

private

  def project_params
    params.require(:project).permit(:title, :organization_id, :user_id, 
      :description, :skills, :deadline)
  end
end

app/views/projects/index.html.haml
.row.row-custom#project-index-wrapper
  .col-lg-10.pull-left.white
    - @projects.each do |project|
      = render 'shared/project_thumbnail', project: project         
  .col-lg-2.pull-right
    %div#project-search-wrapper
      .form-group
        = form_tag search_projects_path, method: 'get' do
          %input.form-control{:placeholder => "Search by project title or project description", :type => "text", :id => "project-search-bar", :name => "search_term"}
          %h3 Project Type
          %label 
            %input{:name => 'project_type[]', :type => "checkbox", :value => "Graphic Design"}
            Graphic Design
          %label
            %input{:name => 'project_type[]', :type => "checkbox", :value => "Web Development"}
            Web Development
          %label
            %input{:name => 'project_type[]', :type => "checkbox", :value => "Accounting"}
            Accounting
          %label 
            %input{:name => 'project_type[]', :type => "checkbox", :value => "Fundraising"}
            Fundraising
          %label 
            %input{:name => 'project_type[]', :type => "checkbox", :value => "Business Consulting"}
            Business Consulting
          %h3 Cause
          %label
            %input{:name => 'causes', :type => "checkbox", :value => "Animals"}
            Animal
          %label 
            %input{:name => 'causes', :type => "checkbox", :value => "Human Rights"}
            Human Rights
          %label
            %input{:name => 'causes', :type => "checkbox", :value => "Social Good"}
            Social Good
          = submit_tag "Search", :id => "project-filter-submit"

app/views/projects/search.html.haml
.row.row-custom#project-index-wrapper
  .col-lg-10.pull-left.white
    - @results.each do |project|
      = render 'shared/project_thumbnail', project: project         
  .col-lg-2.pull-right
    %div#project-search-wrapper 
      .form-group
        = form_tag search_projects_path, method: 'get' do
          %input.form-control{:placeholder => "Search", :type => "text", :id => "project-search-bar", :name => "search_term"}
          %h3 Project Type
          %label 
            %input{:name => 'project_type[]', :type => "checkbox", :value => "Graphic Design"}
            Graphic Design
          %label
            %input{:name => 'project_type[]', :type => "checkbox", :value => "Web Development"}
            Web Development
          %label
            %input{:name => 'project_type[]', :type => "checkbox", :value => "Accounting"}
            Accounting
          %label 
            %input{:name => 'project_type[]', :type => "checkbox", :value => "Fundraising"}
            Fundraising
          %label 
            %input{:name => 'project_type[]', :type => "checkbox", :value => "Business Consulting"}
            Business Consulting
          %h3 Cause
          %label
            %input{:name => 'causes', :type => "checkbox", :value => "Animals"}
            Animal
          %label 
            %input{:name => 'causes', :type => "checkbox", :value => "Human Rights"}
            Human Rights
          %label
            %input{:name => 'causes', :type => "checkbox", :value => "Social Good"}
            Social Good
          = submit_tag "Search", :id => "project-filter-submit"

app/views/projects/show.html.haml
#project-details
  .container-wrapper
    .row.row-custom
      .col-lg-6.col-lg-offset-1.project-board
        %h2 
          = @project.title
        %p 
          = @project.description
        .form-group
          %btn
          - if @project.administrator == current_user
            = link_to "Edit Project", edit_organization_admin_project_path(@project.id), class: "btn btn-primary btn-lg btn-project"
          - elsif @project.state == "open"
            = link_to "Request to Join", new_volunteer_application_path(project_id: @project.id), class: "btn btn-primary btn-lg btn-project" 
          - elsif @project.state == "in production"
            = link_to "Project Complete", new_message_path(project_id: @project.id), class: "btn btn-primary btn-lg btn-project"  
      .col-lg-4
        - if @project.project_admin || @project.volunteers.first == current_user 
          - if @project.state == "open"
            %div.project-notice.open
              %p.bold.text-alert= "Project is #{@project.state}"
          - elsif @project.state == "in production"
            %div.project-notice.open
              %p.bold.text-alert= "Project is #{@project.state}"
          - elsif @project.has_submitted_work?
            %div.project-notice.open
              %p.bold.text-alert= "Project has received work"
          - elsif @project.is_complete?
            %div.project-notice.open
              %p.bold.text-alert= "Project is completed"
          - elsif @project.is_unfinished?
            %div.project-notice.open
              %p.bold.text-alert= "Project is unfinished"
          - else
            %div.project-notice.open
              %p.bold.text-alert= "Project is expired"
        - else
          - if @project.state == "open"
            %div.project-notice.open
              %p.bold.text-alert= "Project is #{@project.state}"
          - else
            %div.project-notice.closed
              %p.bold.text-alert= "Project is closed"
        %p.bold.gr-green-font Deadline
        %div.notice 
          %span= fix_date_time(@project.deadline)
        %p.bold.gr-green-font Cause
        %div.notice 
          %span= @project.causes
        %p.bold.gr-green-font Skills
        %div.notice
          %span= @project.skills.map(&:name).join(', ')
        %p.bold.gr-green-font Estimated Hours
        %div.notice
          %span= @project.estimated_hours
        %p.bold.gr-green-font Organization
        %div.notice-wrapper
          %button.notice
            = link_to @project.organization.name, organization_path(@project.organization.id)
          - if @project.organization.logo?
            = link_to cl_image_tag(@project.organization.logo.path, { size: '35x35', crop: :fit }), project_path(@project.id)
          - else
            = link_to image_tag(@project.organization.small_cover.to_s, size: "35x35"), project_path(@project.id)
        %p.bold.gr-green-font Project Admin
        %div
          %button.notice= link_to "#{@project.project_admin.first_name} #{@project.project_admin.last_name}", user_path(@project.project_admin.id)
          - if @project.project_admin.avatar?
            = cl_image_tag(@project.project_admin.avatar.path, size: "33x33")
          - else
            = image_tag(@project.project_admin.small_cover.to_s, class: "testing")
        %p.bold.gr-green-font= @project.state == "open" ? "Volunteer Requests" : "Project Volunteer"
        - if @project.applicants == []
          %em No volunteer have applied yet. 
        - else
          - @project.applicants.each do |applicant|
            - if applicant.organization != @project.organization
              %div
                %button.notice
                  = link_to "#{applicant.first_name} #{applicant.last_name}", user_path(applicant.id)
                - if applicant.avatar?
                  = cl_image_tag(applicant.avatar.path, size: "33x33")
                - else
                  = image_tag(applicant.small_cover.to_s, class: "testing")
                        
        