config/routes.rb
Grassroots::Application.routes.draw do
  root to: 'pages#home' 
  get 'sign_in', to: 'sessions#new'
  post 'log_in', to: 'sessions#create'
  get 'log_out', to: 'sessions#destroy'

  mount Attachinary::Engine => "/attachinary"

  namespace :organization_admin do
    resources :projects, only: [:new, :create, :edit, :update]
    resources :organizations, only: [:edit, :update, :new, :create]
    resources :volunteer_applications, only: [:index]
  end

  namespace :volunteer do
    resources :volunteer_applications, only: [:index]
  end

  resources :users, except: [:destroy] do
    collection do
      get 'search', to: 'users#search', as: 'search'
    end
  end
  delete 'remove', to: 'users#remove'
  
  resources :organizations, only: [:show, :index] do
    collection do
      get 'search', to: 'organizations#search', as: 'search'
    end
  end
  
  resources :projects, only: [:index, :show] do
    collection do
      get 'search', to: 'projects#search', as: 'search'
    end
  end
  get 'join', to: 'projects#join', as: 'join'

  resources :messages, only: [:new, :create, :index] 
  resources :volunteer_applications, only: [:new, :create]
  resources :contracts, only: [:create, :new, :destroy, :update]
  resources :work_submissions, only: [:new, :create]
  resources :conversations, only: [:show, :index]

  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'

  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'password_resets#expired_token'

  resources :questions, only: [:index, :show, :new, :create, :edit, :update] do
    
    member do
      post '/votes', to: 'questions#vote'
    end

    resources :comments, only: [:create] do
      member do
        post '/votes', to: 'comments#vote'
      end
    end

    resources :answers, only: [:create] do
      member do
        post '/votes', to: 'answers#vote'
      end
      
      resources :comments, only: [:create] do
        member do
          post '/votes', to: 'comments#vote'
        end
      end
    end
  end

  resources :work_conversations, only: [:index]
  resources :categories, only: [:show]
  resources :badges, only: [:show]
  resources :relationships, only: [:create, :destroy]
  resources :newsfeed_items, only: [:index] do
    resources :comments, only: [:create]
  end
  resources :status_updates, only: [:create]

  resources :skills, only: [:create]
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :organization_administrator, foreign_key: 'user_id', class_name: 'User'  
  has_many :projects
  has_many :project_drafts
  has_many :users

  has_attachment :logo, accept: [:jpg, :png, :gif]

  def open_projects
    projects.select do |member|
      member.state == "open" && member.deadline > Date.today
    end
  end

  def in_production_projects
    active_contracts = organization_administrator.delegated_projects.where(active: true, dropped_out: nil, complete: nil, incomplete: nil, work_submitted: false).to_a
    projects_in_production = active_contracts.map do |member|
      Project.find(member.project_id)
    end
    projects_in_production.sort
  end

  def projects_with_work_submitted
    contracts_reflecting_work_submitted = organization_administrator.delegated_projects.where(active: true, work_submitted: true).to_a
    contracts_reflecting_work_submitted.map do |member|
      Project.find(member.project_id)
    end
  end

  def completed_projects
    completed_contracts = organization_administrator.delegated_projects.where(active: false, work_submitted: true, complete: true, incomplete: false).to_a
    completed_contracts.map do |member|
      Project.find(member.project_id)
    end
  end

  def unfinished_projects
    unfinished_contracts = organization_administrator.delegated_projects.where(incomplete: true).to_a
    unfinished_contracts.map do |member|
      Project.find(member.project_id)
    end
  end

  def expired_projects
    projects.select do |member|
      member.deadline < Date.today
    end
  end

  def self.search_by_name(search_term)
    return [] if search_term.blank?
    where("name LIKE ?", "%#{search_term}%")
  end
end

app/controllers/organization_admin/organizations_controller.rb
class OrganizationAdmin::OrganizationsController < OrganizationAdminController
  before_action :find_organization, only: [:update, :edit]
  
  def new
    @organization = Organization.new
  end

  def edit; end

  def update
    @organization.update_columns(organization_params)
    uploading_logo?(@organization)
    flash[:notice] = "You have updated your organization's profile."
    redirect_to organization_path(@organization.id)
  end

  def create
    @organization = Organization.new(organization_params.merge!(user_id: current_user.id))
    @organization.save
    current_user.update_columns(organization_id: @organization.id)
    flash[:success] = "You created your organization."
    redirect_to organization_path(@organization.id)
  end

private

  def organization_params
    params.require(:organization).permit(:name, :date_of_incorporation, 
      :ein, :street1, :street2, :city, :state_abbreviation, :zip, :cause, 
      :contact_number, :contact_email, :mission_statement, :goal, :user_id)
  end

  def uploading_logo?(a_organization)
    if params[:organization][:logo]
      a_organization.logo = params[:organization][:logo]
      a_organization.logo.save
    end
  end

  def find_organization
    @organization = Organization.find(params[:id])
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :find_organization, only: [:show]
  
  def show
    @open_params = params[:tab] == 'open'
    @production_params = params[:tab] == 'in production'
    @work_submitted_params = params[:tab] == 'pending approval'
    @completed_params = params[:tab] == 'completed'
    @unifinished_params = params[:tab] == 'unfinished'
    @expired_params = params[:tab] == 'expired'
    @drafts_params = params[:tab] == 'drafts'

    @open_projects = @organization.open_projects
    @in_production_projects = @organization.in_production_projects
    @projects_with_work_submitted = @organization.projects_with_work_submitted
    @completed_projects = @organization.completed_projects
    @unfinished_projects = @organization.unfinished_projects
    @expired_projects = @organization.expired_projects
    
    @project_drafts = @organization.project_drafts

    respond_to do |format|
      format.html do
      end
      format.js
    end
  end

  def index
    @organizations = Organization.all
  end

  def search
    filter = {cause: params[:cause]} if params[:cause]
    
    if filter != nil
      @results = Organization.where(filter).to_a
      @results.sort! {|x,y| x.name <=> y.name }
    else
      @results = Organization.search_by_name(params[:search_term])
    end 
  end

private

  def organization_params
    params.require(:organization).permit(:name, :date_of_incorporation, 
      :ein, :street1, :street2, :city, :state_abbreviation, :zip, :cause, 
      :contact_number, :contact_email, :mission_statement, :goal, :user_id)
  end

  def find_organization
    @organization = Organization.find(params[:id])
  end
end

app/views/organizations/index.html.haml
.col-lg-3.pull-right                 
  = form_tag search_organizations_path, method: 'get' do
    %input.form-control{:placeholder => "Search by organization name", :type => "text", :id => "project-search-bar", :name => "search_term"}
    %h3 Cause
    %label 
      %input{:name => 'cause[]', :type => "checkbox", :value => "Human Rights"}
      Human Rights
    %label 
      %input{:name => 'cause[]', :type => "checkbox", :value => "Social Good"}
      Social Good
    %label 
      %input{:name => 'cause[]', :type => "checkbox", :value => "Animal Rights"}
      Animal Rights
    = submit_tag "Search", :id => "project-filter-submit"

app/views/organizations/search.html.haml
.col-lg-2.pull-right               
  = form_tag search_organizations_path, method: 'get' do
    %input.form-control{:placeholder => "Search by organization name", :type => "text", :id => "project-search-bar", :name => "search_term"}
    %h3 Cause
    %label 
      %input{:name => 'cause', :type => "checkbox", :value => "Human Rights"}
      Human Rights
    %label 
      %input{:name => 'cause', :type => "checkbox", :value => "Social Good"}
      Social Good
    %label 
      %input{:name => 'cause', :type => "checkbox", :value => "Animal Rights"}
      Animal Rights
    = submit_tag "Search", :id => "project-filter-submit"
.row#org-search-results
  - @results.each do |organization|
    = render "shared/organization_thumbnail", organization: organization

app/views/organizations/show.html.haml
.row#profile-details-row
  .col-lg-3
    - if @organization.logo?
      = cl_image_tag(@organization.logo.path, { size: '150x150', crop: :fit })
    - else
      = image_tag(@organization.small_cover.to_s, size: "150x150")
  .col-lg-8#org-info
    %h2 
      = @organization.name
    .row
      .col-lg-4#org-header-info
        %h5.header-spacing 
          %strong 
            = "#{@organization.city}"
        %h5.header-spacing 
          %strong 
            = "#{@organization.cause}"
      %p.pull-right
        = link_to "Edit Organization Profile", edit_organization_admin_organization_path(@organization) if current_user.organization_administrator && current_user.organization_id == @organization.id
  .col-lg-12
    %ul.nav.nav-tabs#myTab
      %li.active
        %a{:href => "#activity", 'data-toggle' => "tab"} Activity
      %li
        %a{:href => "#overview", 'data-toggle' => "tab"} Overview
      
.tab-content
  .tab-pane.active#activity
    .container-wrapper 
      .row.row-custom
        .col-lg-6
          %h2 Projects
        .col-lg-6
          %btn
            = link_to "Create a Project", new_organization_admin_project_path(organization_id: @organization.id), class: "btn btn-primary btn-lg pull-right btn-project" if current_user.organization_administrator

    .row
      %ul.nav.nav-tabs
        %li{:class => ('active' if params[:tab] == 'open')}
          = link_to "Available Projects #{@organization.open_projects.count}", organization_path(@organization, tab: 'open'), remote: true
        
        %li{:class => ('active' if params[:tab] == 'in production')}
          = link_to "Projects in Production #{@organization.in_production_projects.count}",  organization_path(@organization, tab: 'in production'), remote: true
      
        %li{:class => ('active' if params[:tab] == 'pending approval')}
          = link_to "Completion Request #{@organization.projects_with_work_submitted.count}", organization_path(@organization, tab: 'pending approval'), remote: true
      
        %li{:class => ('active' if params[:tab] == 'completed')}
          = link_to "Completed Projects #{@organization.completed_projects.count}", organization_path(@organization, tab: 'completed'), remote: true
      
        %li{:class => ('active' if params[:tab] == 'unfinished')}
          = link_to "Unfinished #{@organization.unfinished_projects.count}", organization_path(@organization, tab: 'unfinished'), remote: true

        %li{:class => ('active' if params[:tab] == 'expired')}
          = link_to "Expired #{@organization.expired_projects.count}", organization_path(@organization, tab: 'expired'), remote: true

        %li{:class => ('active' if params[:tab] == 'drafts')}
          = link_to "Drafts #{@organization.project_drafts.count}", organization_path(@organization, tab: 'drafts'), remote: true

      .col-lg-10
        %div{:id => "projectsDiv"}

  .tab-pane#overview
    .row.row-custom
      .col-lg-12
        %h2 Organization Information

    .row#org-data-wrapper 
      .col-lg-12
        .col-lg-8
          %dl 
            %dt Mission
            %dd
              = @organization.mission_statement
          %dl 
            %dt Goals 
            %dd 
              = @organization.goal
          .row
            .col-lg-8#org-data-pts
              %div.pull-left.org-data EIN Number:
              %div= @organization.ein
              %div.pull-left.org-data Organization Budget:
              %div= @organization.budget
              %div.pull-left.org-data Organization Size:
              %div= @organization.users.count
              %div.pull-left.org-data Founding Year:
              %div= @organization.ruling_year
          .row
            .col-lg-8
              %dl#org-address-line
                %dt Physical Address
                %dd
                  = @organization.street1
                  = "#{@organization.street2}"
                  %br
                  = "#{@organization.city},"
                  = @organization.state_abbreviation
                  = @organization.zip
              %div.pull-left.org-data Contact Number:
              %div= @organization.contact_number
              %div.pull-left.org-data Contact Email:
              %div= @organization.contact_email

    .row.row-custom
      .col-lg-12
        %h2 Staff
        

    .container-wrapper 
      .row#staff-wrapper
        - @organization.users.each do |user|
          = render 'shared/user_thumbnail', user: user

app/views/organizations/show.js.erb
<%if @open_params %>
	<% if @open_projects.empty?%>
		$('#projectsDiv').empty()
  	$('#projectsDiv').append('<p> <%= j render "shared/empty_project_thumbnail" %></p>')
	<% else %>
		$('#projectsDiv').empty()
		"<% @open_projects.each do |project| %>"
			$('#projectsDiv').append('<p> <%= j render "shared/project_thumbnail", project: project %></p>')
		"<% end %>"
	<% end %>
<% elsif @production_params %>
	<% if @in_production_projects.empty? %>
		$('#projectsDiv').empty()
  	$('#projectsDiv').append('<p> <%= j render "shared/empty_project_thumbnail" %></p>')
	<% else %>
		$('#projectsDiv').empty()
	"<% @in_production_projects.each do |project| %>"
		$('#projectsDiv').append('<p> <%= j render "shared/project_thumbnail", project: project %></p>')
	"<% end %>"
	<% end %>
<% elsif @work_submitted_params %>
	<% if @projects_with_work_submitted.empty?%>
		$('#projectsDiv').empty()
  	$('#projectsDiv').append('<p> <%= j render "shared/empty_project_thumbnail" %></p>')
	<% else %>
		$('#projectsDiv').empty()
		"<% @projects_with_work_submitted.each do |project| %>"
	  	$('#projectsDiv').append('<p> <%= j render "shared/project_thumbnail", project: project %></p>')
		"<% end %>"
	<% end %>
<% elsif @completed_params %>
	<% if @completed_projects.empty?%>
		$('#projectsDiv').empty()
  	$('#projectsDiv').append('<p> <%= j render "shared/empty_project_thumbnail" %></p>')
	<% else %>
		$('#projectsDiv').empty()
		"<% @completed_projects.each do |project| %>"
	  	$('#projectsDiv').append('<p> <%= j render "shared/project_thumbnail", project: project %></p>')
		"<% end %>"
	<% end %>
<% elsif @unifinished_params %>
	<% if @unfinished_projects.empty?%>
		$('#projectsDiv').empty()
  	$('#projectsDiv').append('<p> <%= j render "shared/empty_project_thumbnail" %></p>')
	<% else %>
		$('#projectsDiv').empty()
		"<% @unfinished_projects.each do |project| %>"
		  $('#projectsDiv').append('<p> <%= j render "shared/project_thumbnail", project: project %></p>');
		"<% end %>"
	<% end %>
<% elsif @expired_params %>
	<% if @expired_projects.empty?%>
		$('#projectsDiv').empty()
  	$('#projectsDiv').append('<p> <%= j render "shared/empty_project_thumbnail" %></p>')
	<% else %>
		$('#projectsDiv').empty()
		"<% @expired_projects.each do |project| %>"
	  	$('#projectsDiv').append('<p> <%= j render "shared/project_thumbnail", project: project %></p>');
		"<% end %>"
	<% end %>
<% else %>
	<% if @project_drafts.empty?%>
		$('#projectsDiv').empty()
  	$('#projectsDiv').append('<p> <%= j render "shared/empty_project_thumbnail" %></p>')
	<% else %>
		$('#projectsDiv').empty()
		"<% @project_drafts.each do |draft| %>"
	  	$('#projectsDiv').append('<p> <%= j render "shared/project_draft_thumbnail", draft: draft %></p>');
		"<% end %>"
	<% end %>
<% end %>